version: "3"

services:

  backend:

    build: backend/

    command: go build -o main .

    ports:
      - 5173:5173

  frontend:

    build: frontend/

    command: npm start

    network_mode: host

    depends_on:
      - backend